path: './data/'

features: 
    f1:
        func: cal_WAP1 #function name
        name: 'WAP1' #defined col name
    f2:
        func: cal_WAP2
        name: 'WAP2'
    f3:
        func: cal_WAP3
        name: 'WAP3'
    f4:
        func: cal_WAP4
        name: 'WAP4'
