path: './data/'

features: 
    b1:
        func: cal_WAP1 #function name
        name: 'WAP1' #defined col name
        Ex_win_size: [100, 200] # extra window size, exclude 600 (default)
    b2:
        func: cal_WAP2
        name: 'WAP2'
        Ex_win_size: [100]
    b3:
        func: cal_WAP3
        name: 'WAP3'
        Ex_win_size: [100]
    b4:
        func: cal_WAP4
        name: 'WAP4'
        Ex_win_size: []
    o1:
        func: 
        name: 'price'
        Ex_win_size: []